customhost = "employee.c5fcgxlm0oiz.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "pekjuenyee-employee"
customregion = "us-east-1"